[package]
name = "frontend"
version = "0.5.2"
edition = "2021"
publish = false

[dependencies]
chrono = { version = "0.4.23", features = ["serde"] }
gloo-storage = "0.2.2"
gloo-utils = "0.1.6"
log = "0.4.17"
serde = { version = "1.0.148", features = ["serde_derive"] }
serde_json = "1.0.89"
shared = { path = "../shared" }
stylist = { version = "0.11.0", features = ["parser", "yew_integration"] }
wasm-bindgen = "0.2.83"
wasm-bindgen-futures = "0.4.33"
wasm-logger = "0.2.0"
yew = { version = "0.20.0", features = ["csr"] }
yew-hooks = "0.2.0"
yew-router = "0.17.0"
serde_urlencoded = "0.7.1"

[dependencies.web-sys]
version = "0.3.60"
features = [
    "Document",
    "Headers",
    "HtmlInputElement",
    "Location",
    "Request",
    "RequestInit",
    "RequestMode",
    "Response",
    "ScrollBehavior",
    "ScrollToOptions",
    "Window",
]
