[package]
name = "calibre"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
chrono = { version = "0.4.20", features = ["serde"] }
diesel = { version = "1.4.8", features = ["chrono", "sqlite", "r2d2"] }
dotenv = "0.15.0"
log = "0.4.17"
r2d2 = "0.8.10"
serde = { version = "1.0.142", features = ["derive"] }
serde_json = "1.0.83"
